my.server.port: -1
my.noprofile.value.in.yml: 333
---
spring:
  profiles: local
my.server.port: 8080
---
spring:
  profiles: dev
my.server.port: 8081
---
spring:
  profiles: prod
my.server.port: 8082
