spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/refactoring-test
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_fetch_batch_size: 100
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true

logging:
  level: 
    root: debug
